# Futures long or short position

<br><br><br>

### Get page with data in last 4 hours

In [170]:
### import packages
import requests
import time
from selenium.webdriver import Chrome
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

In [159]:
driver = Chrome(service=Service(ChromeDriverManager().install()))
driver.maximize_window()

In [160]:
driver.get("https://www.binance.com/en/futures/funding-history/4")
time.sleep(3)

In [161]:
actions = ActionChains(driver)
sections = driver.find_elements(By.CLASS_NAME, 'css-w7nhq2')

xp = 1

while xp <= len(sections):
    time.sleep(.5)
    section = driver.find_element(By.XPATH, f'//*[@id="__APP"]/div/div[2]/div[1]/div[2]/div[6]/div/div[1]/div[2]/div/button[{xp}]')
    actions.move_to_element(section)
    actions.click(section)
    
    hour_buttons = driver.find_element(By.XPATH, f'//*[@id="__APP"]/div/div[2]/div[1]/div[2]/div[6]/div/div[2]/div[{xp}]/div[1]/div[2]/div/div/div')
    
    actions.move_to_element(hour_buttons)
    actions.click(hour_buttons)
    
    if xp == 1 or xp == 5:
        open_button = driver.find_element(By.XPATH, f'/html/body/div[1]/div/div[2]/div[1]/div[2]/div[6]/div/div[2]/div[{xp}]/div[1]/div[2]/div/div/div/div[3]/ul/li[6]')
    else:
        open_button = driver.find_element(By.XPATH, f'/html/body/div[1]/div/div[2]/div[1]/div[2]/div[6]/div/div[2]/div[{xp}]/div[1]/div[2]/div/div/div[3]/ul/li[6]')
    
    actions.move_to_element(open_button)
    actions.click(open_button)
    
    xp+=1
    
    actions.perform()

## scrap data

In [162]:
from bs4 import BeautifulSoup

In [163]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
sections = soup.find_all('div', class_='css-2ceisz')
len(sections)

5

In [165]:
section1 = sections[0]
times1 = section1.find_all('g', class_='highcharts-xaxis-labels')
section1Times = []


for time in times1[0]:
    section1Times.append(time.text)

section1Times

['20:00',
 '00:00',
 '04:00',
 '08:00',
 '12:00',
 '16:00',
 '20:00',
 '00:00',
 '04:00',
 '08:00',
 '12:00',
 '16:00',
 '20:00',
 '00:00',
 '04:00',
 '08:00',
 '12:00',
 '16:00',
 '20:00',
 '00:00',
 '04:00',
 '08:00',
 '12:00',
 '16:00',
 '20:00',
 '00:00',
 '04:00',
 '08:00',
 '12:00',
 '16:00']

In [168]:
section1 = sections[0]
pricesSection = section1.find_all(lambda tag: tag.name == "rect")

prices = []
k = 0
while k < len(pricesSection)-2:
    try:
        if pricesSection[k]['class'] == ['highcharts-point']:
            prices.append(pricesSection[k]['y'])
        k+=1
    except:
        k+=1
        
prices

['95',
 '94',
 '101',
 '101',
 '99',
 '102',
 '103',
 '116',
 '122',
 '120',
 '117',
 '94',
 '74',
 '69',
 '73',
 '65',
 '58',
 '56',
 '56',
 '76',
 '87',
 '84',
 '82',
 '81',
 '71',
 '82',
 '82',
 '82',
 '91',
 '89']

In [172]:
d = {
     'Time': section1Times, 
     'Open Interest': prices,
    }
df = pd.DataFrame(data=d)
df

     Time Open Interest
0   20:00            95
1   00:00            94
2   04:00           101
3   08:00           101
4   12:00            99
5   16:00           102
6   20:00           103
7   00:00           116
8   04:00           122
9   08:00           120
10  12:00           117
11  16:00            94
12  20:00            74
13  00:00            69
14  04:00            73
15  08:00            65
16  12:00            58
17  16:00            56
18  20:00            56
19  00:00            76
20  04:00            87
21  08:00            84
22  12:00            82
23  16:00            81
24  20:00            71
25  00:00            82
26  04:00            82
27  08:00            82
28  12:00            91
29  16:00            89